# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, myConfig, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/50d74d28-1334-44ac-9cf3-cafc977d9fff";
      fsType = "ext4";
    };

  fileSystems."/data" =
    {
      device = "/dev/disk/by-uuid/1ae6b3d0-beef-46e7-8832-75d778c7dc9f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-efbc9f75-3a38-469f-af7c-55e17e5c57ff".device = "/dev/disk/by-uuid/efbc9f75-3a38-469f-af7c-55e17e5c57ff";
  boot.initrd.luks.devices."luks-41924bdd-eac8-407b-a28f-38b152fafa9f".device = "/dev/disk/by-uuid/41924bdd-eac8-407b-a28f-38b152fafa9f";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/79D3-506C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
